root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/academic-provider ./cmd/academic-provider"
bin = "./tmp/academic-provider"
include_ext = ["go", "yaml"]
exclude_dir = [".git", ".local", "deploy", "tmp", "vendor"]

[log]
time = true
