// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: academic/analytics/v1/analytics.proto

package academicanalyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AcademicAnalyticsService_ListCoursePassRates_FullMethodName        = "/academic.analytics.v1.AcademicAnalyticsService/ListCoursePassRates"
	AcademicAnalyticsService_ListInstructorPassRates_FullMethodName    = "/academic.analytics.v1.AcademicAnalyticsService/ListInstructorPassRates"
	AcademicAnalyticsService_GetCoursePassRateTrend_FullMethodName     = "/academic.analytics.v1.AcademicAnalyticsService/GetCoursePassRateTrend"
	AcademicAnalyticsService_GetInstructorPassRateTrend_FullMethodName = "/academic.analytics.v1.AcademicAnalyticsService/GetInstructorPassRateTrend"
	AcademicAnalyticsService_ListBatches_FullMethodName                = "/academic.analytics.v1.AcademicAnalyticsService/ListBatches"
	AcademicAnalyticsService_TriggerManualRun_FullMethodName           = "/academic.analytics.v1.AcademicAnalyticsService/TriggerManualRun"
)

// AcademicAnalyticsServiceClient is the client API for AcademicAnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AcademicAnalyticsService exposes published, aggregate-only academic data.
// It must never return student-level grades or identities.
type AcademicAnalyticsServiceClient interface {
	ListCoursePassRates(ctx context.Context, in *ListCoursePassRatesRequest, opts ...grpc.CallOption) (*ListCoursePassRatesResponse, error)
	ListInstructorPassRates(ctx context.Context, in *ListInstructorPassRatesRequest, opts ...grpc.CallOption) (*ListInstructorPassRatesResponse, error)
	GetCoursePassRateTrend(ctx context.Context, in *GetCoursePassRateTrendRequest, opts ...grpc.CallOption) (*GetCoursePassRateTrendResponse, error)
	GetInstructorPassRateTrend(ctx context.Context, in *GetInstructorPassRateTrendRequest, opts ...grpc.CallOption) (*GetInstructorPassRateTrendResponse, error)
	ListBatches(ctx context.Context, in *ListBatchesRequest, opts ...grpc.CallOption) (*ListBatchesResponse, error)
	TriggerManualRun(ctx context.Context, in *TriggerManualRunRequest, opts ...grpc.CallOption) (*TriggerManualRunResponse, error)
}

type academicAnalyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademicAnalyticsServiceClient(cc grpc.ClientConnInterface) AcademicAnalyticsServiceClient {
	return &academicAnalyticsServiceClient{cc}
}

func (c *academicAnalyticsServiceClient) ListCoursePassRates(ctx context.Context, in *ListCoursePassRatesRequest, opts ...grpc.CallOption) (*ListCoursePassRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCoursePassRatesResponse)
	err := c.cc.Invoke(ctx, AcademicAnalyticsService_ListCoursePassRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicAnalyticsServiceClient) ListInstructorPassRates(ctx context.Context, in *ListInstructorPassRatesRequest, opts ...grpc.CallOption) (*ListInstructorPassRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstructorPassRatesResponse)
	err := c.cc.Invoke(ctx, AcademicAnalyticsService_ListInstructorPassRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicAnalyticsServiceClient) GetCoursePassRateTrend(ctx context.Context, in *GetCoursePassRateTrendRequest, opts ...grpc.CallOption) (*GetCoursePassRateTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoursePassRateTrendResponse)
	err := c.cc.Invoke(ctx, AcademicAnalyticsService_GetCoursePassRateTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicAnalyticsServiceClient) GetInstructorPassRateTrend(ctx context.Context, in *GetInstructorPassRateTrendRequest, opts ...grpc.CallOption) (*GetInstructorPassRateTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstructorPassRateTrendResponse)
	err := c.cc.Invoke(ctx, AcademicAnalyticsService_GetInstructorPassRateTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicAnalyticsServiceClient) ListBatches(ctx context.Context, in *ListBatchesRequest, opts ...grpc.CallOption) (*ListBatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBatchesResponse)
	err := c.cc.Invoke(ctx, AcademicAnalyticsService_ListBatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academicAnalyticsServiceClient) TriggerManualRun(ctx context.Context, in *TriggerManualRunRequest, opts ...grpc.CallOption) (*TriggerManualRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerManualRunResponse)
	err := c.cc.Invoke(ctx, AcademicAnalyticsService_TriggerManualRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademicAnalyticsServiceServer is the server API for AcademicAnalyticsService service.
// All implementations must embed UnimplementedAcademicAnalyticsServiceServer
// for forward compatibility.
//
// AcademicAnalyticsService exposes published, aggregate-only academic data.
// It must never return student-level grades or identities.
type AcademicAnalyticsServiceServer interface {
	ListCoursePassRates(context.Context, *ListCoursePassRatesRequest) (*ListCoursePassRatesResponse, error)
	ListInstructorPassRates(context.Context, *ListInstructorPassRatesRequest) (*ListInstructorPassRatesResponse, error)
	GetCoursePassRateTrend(context.Context, *GetCoursePassRateTrendRequest) (*GetCoursePassRateTrendResponse, error)
	GetInstructorPassRateTrend(context.Context, *GetInstructorPassRateTrendRequest) (*GetInstructorPassRateTrendResponse, error)
	ListBatches(context.Context, *ListBatchesRequest) (*ListBatchesResponse, error)
	TriggerManualRun(context.Context, *TriggerManualRunRequest) (*TriggerManualRunResponse, error)
	mustEmbedUnimplementedAcademicAnalyticsServiceServer()
}

// UnimplementedAcademicAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcademicAnalyticsServiceServer struct{}

func (UnimplementedAcademicAnalyticsServiceServer) ListCoursePassRates(context.Context, *ListCoursePassRatesRequest) (*ListCoursePassRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoursePassRates not implemented")
}
func (UnimplementedAcademicAnalyticsServiceServer) ListInstructorPassRates(context.Context, *ListInstructorPassRatesRequest) (*ListInstructorPassRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstructorPassRates not implemented")
}
func (UnimplementedAcademicAnalyticsServiceServer) GetCoursePassRateTrend(context.Context, *GetCoursePassRateTrendRequest) (*GetCoursePassRateTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoursePassRateTrend not implemented")
}
func (UnimplementedAcademicAnalyticsServiceServer) GetInstructorPassRateTrend(context.Context, *GetInstructorPassRateTrendRequest) (*GetInstructorPassRateTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstructorPassRateTrend not implemented")
}
func (UnimplementedAcademicAnalyticsServiceServer) ListBatches(context.Context, *ListBatchesRequest) (*ListBatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBatches not implemented")
}
func (UnimplementedAcademicAnalyticsServiceServer) TriggerManualRun(context.Context, *TriggerManualRunRequest) (*TriggerManualRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerManualRun not implemented")
}
func (UnimplementedAcademicAnalyticsServiceServer) mustEmbedUnimplementedAcademicAnalyticsServiceServer() {
}
func (UnimplementedAcademicAnalyticsServiceServer) testEmbeddedByValue() {}

// UnsafeAcademicAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcademicAnalyticsServiceServer will
// result in compilation errors.
type UnsafeAcademicAnalyticsServiceServer interface {
	mustEmbedUnimplementedAcademicAnalyticsServiceServer()
}

func RegisterAcademicAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AcademicAnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAcademicAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcademicAnalyticsService_ServiceDesc, srv)
}

func _AcademicAnalyticsService_ListCoursePassRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCoursePassRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicAnalyticsServiceServer).ListCoursePassRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicAnalyticsService_ListCoursePassRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicAnalyticsServiceServer).ListCoursePassRates(ctx, req.(*ListCoursePassRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicAnalyticsService_ListInstructorPassRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstructorPassRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicAnalyticsServiceServer).ListInstructorPassRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicAnalyticsService_ListInstructorPassRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicAnalyticsServiceServer).ListInstructorPassRates(ctx, req.(*ListInstructorPassRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicAnalyticsService_GetCoursePassRateTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoursePassRateTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicAnalyticsServiceServer).GetCoursePassRateTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicAnalyticsService_GetCoursePassRateTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicAnalyticsServiceServer).GetCoursePassRateTrend(ctx, req.(*GetCoursePassRateTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicAnalyticsService_GetInstructorPassRateTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstructorPassRateTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicAnalyticsServiceServer).GetInstructorPassRateTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicAnalyticsService_GetInstructorPassRateTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicAnalyticsServiceServer).GetInstructorPassRateTrend(ctx, req.(*GetInstructorPassRateTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicAnalyticsService_ListBatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicAnalyticsServiceServer).ListBatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicAnalyticsService_ListBatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicAnalyticsServiceServer).ListBatches(ctx, req.(*ListBatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademicAnalyticsService_TriggerManualRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerManualRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademicAnalyticsServiceServer).TriggerManualRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcademicAnalyticsService_TriggerManualRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademicAnalyticsServiceServer).TriggerManualRun(ctx, req.(*TriggerManualRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcademicAnalyticsService_ServiceDesc is the grpc.ServiceDesc for AcademicAnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcademicAnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.analytics.v1.AcademicAnalyticsService",
	HandlerType: (*AcademicAnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCoursePassRates",
			Handler:    _AcademicAnalyticsService_ListCoursePassRates_Handler,
		},
		{
			MethodName: "ListInstructorPassRates",
			Handler:    _AcademicAnalyticsService_ListInstructorPassRates_Handler,
		},
		{
			MethodName: "GetCoursePassRateTrend",
			Handler:    _AcademicAnalyticsService_GetCoursePassRateTrend_Handler,
		},
		{
			MethodName: "GetInstructorPassRateTrend",
			Handler:    _AcademicAnalyticsService_GetInstructorPassRateTrend_Handler,
		},
		{
			MethodName: "ListBatches",
			Handler:    _AcademicAnalyticsService_ListBatches_Handler,
		},
		{
			MethodName: "TriggerManualRun",
			Handler:    _AcademicAnalyticsService_TriggerManualRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "academic/analytics/v1/analytics.proto",
}
