-- module: academic_statistics
CREATE TABLE academic_statistics_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  status VARCHAR(16) NOT NULL,
  source_cutoff_at DATETIME(3) NOT NULL,
  rule_version VARCHAR(32) NOT NULL,
  source_row_count BIGINT NOT NULL,
  course_stat_count BIGINT NOT NULL,
  instructor_stat_count BIGINT NOT NULL,
  error_summary VARCHAR(1000) NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  published_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_academic_statistics_batch_publication (status, published_at)
);
CREATE TABLE academic_course_term_statistics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  term_code VARCHAR(50) NOT NULL,
  course_code VARCHAR(50) NOT NULL,
  course_name VARCHAR(255) NOT NULL,
  valid_count BIGINT NOT NULL,
  pass_count BIGINT NOT NULL,
  fail_count BIGINT NOT NULL,
  numeric_fail_count BIGINT NOT NULL,
  score_60_69_count BIGINT NOT NULL,
  score_70_79_count BIGINT NOT NULL,
  score_80_89_count BIGINT NOT NULL,
  score_90_100_count BIGINT NOT NULL,
  level_excellent_count BIGINT NOT NULL,
  level_good_count BIGINT NOT NULL,
  level_medium_count BIGINT NOT NULL,
  level_pass_count BIGINT NOT NULL,
  level_fail_count BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_academic_course_term_stat (batch_id, term_code, course_code),
  KEY idx_academic_course_stat_lookup (batch_id, course_code, term_code),
  CONSTRAINT fk_academic_course_term_statistics_batch_id FOREIGN KEY (batch_id) REFERENCES academic_statistics_batches(id) ON DELETE CASCADE
);
CREATE TABLE academic_instructor_course_term_statistics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  term_code VARCHAR(50) NOT NULL,
  course_code VARCHAR(50) NOT NULL,
  course_name VARCHAR(255) NOT NULL,
  teacher_key VARCHAR(64) NOT NULL,
  teacher_name VARCHAR(100) NOT NULL,
  class_count BIGINT NOT NULL,
  valid_count BIGINT NOT NULL,
  pass_count BIGINT NOT NULL,
  fail_count BIGINT NOT NULL,
  numeric_fail_count BIGINT NOT NULL,
  score_60_69_count BIGINT NOT NULL,
  score_70_79_count BIGINT NOT NULL,
  score_80_89_count BIGINT NOT NULL,
  score_90_100_count BIGINT NOT NULL,
  level_excellent_count BIGINT NOT NULL,
  level_good_count BIGINT NOT NULL,
  level_medium_count BIGINT NOT NULL,
  level_pass_count BIGINT NOT NULL,
  level_fail_count BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_academic_instructor_course_term_stat (batch_id, term_code, course_code, teacher_key),
  KEY idx_academic_instructor_stat_lookup (batch_id, course_code, teacher_key, term_code),
  CONSTRAINT fk_academic_instructor_course_term_statistics_batch_id FOREIGN KEY (batch_id) REFERENCES academic_statistics_batches(id) ON DELETE CASCADE
);
