// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_statistics.yaml

package domain

import "time"

// AcademicStatisticsBatch is the persistent domain entity for the academic_statistics module.
type AcademicStatisticsBatch struct {
	ID                  uint64     `gorm:"primaryKey;autoIncrement" json:"id"`
	Status              string     `gorm:"column:status;not null;index" json:"status"`
	TriggerType         string     `gorm:"column:trigger_type;not null" json:"trigger_type"`
	TriggeredBy         *uint64    `gorm:"column:triggered_by" json:"triggered_by"`
	TriggerNote         *string    `gorm:"column:trigger_note" json:"trigger_note"`
	TriggerTaskId       *string    `gorm:"column:trigger_task_id" json:"trigger_task_id"`
	SourceCutoffAt      time.Time  `gorm:"column:source_cutoff_at;not null" json:"source_cutoff_at"`
	RuleVersion         string     `gorm:"column:rule_version;not null" json:"rule_version"`
	SourceRowCount      int64      `gorm:"column:source_row_count;not null" json:"source_row_count"`
	CourseStatCount     int64      `gorm:"column:course_stat_count;not null" json:"course_stat_count"`
	CoursePassRateCount int64      `gorm:"column:course_pass_rate_count;not null" json:"course_pass_rate_count"`
	MinimumSampleSize   int64      `gorm:"column:minimum_sample_size;not null" json:"minimum_sample_size"`
	InstructorStatCount int64      `gorm:"column:instructor_stat_count;not null" json:"instructor_stat_count"`
	ErrorSummary        *string    `gorm:"column:error_summary" json:"error_summary"`
	StartedAt           time.Time  `gorm:"column:started_at;not null" json:"started_at"`
	FinishedAt          *time.Time `gorm:"column:finished_at" json:"finished_at"`
	PublishedAt         *time.Time `gorm:"column:published_at;index" json:"published_at"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

// TableName returns the schema-controlled database table.
func (AcademicStatisticsBatch) TableName() string { return "academic_statistics_batches" }
