// Code generated by campusctl from a module schema. DO NOT EDIT.
// Source: schemas/academic_statistics.yaml

package domain

import "context"

// Repository defines persistence operations enabled by the module schema.
type Repository interface {
	Get(context.Context, uint64) (*AcademicStatisticsBatch, error)
	List(context.Context, int, int) ([]AcademicStatisticsBatch, int64, error)
}
