// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/weouc-plus/campus-academic/internal/modules/academic_statistics/domain"
)

func newAcademicStatisticsBatch(db *gorm.DB, opts ...gen.DOOption) academicStatisticsBatch {
	_academicStatisticsBatch := academicStatisticsBatch{}

	_academicStatisticsBatch.academicStatisticsBatchDo.UseDB(db, opts...)
	_academicStatisticsBatch.academicStatisticsBatchDo.UseModel(&domain.AcademicStatisticsBatch{})

	tableName := _academicStatisticsBatch.academicStatisticsBatchDo.TableName()
	_academicStatisticsBatch.ALL = field.NewAsterisk(tableName)
	_academicStatisticsBatch.ID = field.NewUint64(tableName, "id")
	_academicStatisticsBatch.Status = field.NewString(tableName, "status")
	_academicStatisticsBatch.TriggerType = field.NewString(tableName, "trigger_type")
	_academicStatisticsBatch.TriggeredBy = field.NewUint64(tableName, "triggered_by")
	_academicStatisticsBatch.TriggerNote = field.NewString(tableName, "trigger_note")
	_academicStatisticsBatch.TriggerTaskId = field.NewString(tableName, "trigger_task_id")
	_academicStatisticsBatch.SourceCutoffAt = field.NewTime(tableName, "source_cutoff_at")
	_academicStatisticsBatch.RuleVersion = field.NewString(tableName, "rule_version")
	_academicStatisticsBatch.SourceRowCount = field.NewInt64(tableName, "source_row_count")
	_academicStatisticsBatch.CourseStatCount = field.NewInt64(tableName, "course_stat_count")
	_academicStatisticsBatch.InstructorStatCount = field.NewInt64(tableName, "instructor_stat_count")
	_academicStatisticsBatch.ErrorSummary = field.NewString(tableName, "error_summary")
	_academicStatisticsBatch.StartedAt = field.NewTime(tableName, "started_at")
	_academicStatisticsBatch.FinishedAt = field.NewTime(tableName, "finished_at")
	_academicStatisticsBatch.PublishedAt = field.NewTime(tableName, "published_at")
	_academicStatisticsBatch.CreatedAt = field.NewTime(tableName, "created_at")
	_academicStatisticsBatch.UpdatedAt = field.NewTime(tableName, "updated_at")

	_academicStatisticsBatch.fillFieldMap()

	return _academicStatisticsBatch
}

type academicStatisticsBatch struct {
	academicStatisticsBatchDo academicStatisticsBatchDo

	ALL                 field.Asterisk
	ID                  field.Uint64
	Status              field.String
	TriggerType         field.String
	TriggeredBy         field.Uint64
	TriggerNote         field.String
	TriggerTaskId       field.String
	SourceCutoffAt      field.Time
	RuleVersion         field.String
	SourceRowCount      field.Int64
	CourseStatCount     field.Int64
	InstructorStatCount field.Int64
	ErrorSummary        field.String
	StartedAt           field.Time
	FinishedAt          field.Time
	PublishedAt         field.Time
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a academicStatisticsBatch) Table(newTableName string) *academicStatisticsBatch {
	a.academicStatisticsBatchDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a academicStatisticsBatch) As(alias string) *academicStatisticsBatch {
	a.academicStatisticsBatchDo.DO = *(a.academicStatisticsBatchDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *academicStatisticsBatch) updateTableName(table string) *academicStatisticsBatch {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.Status = field.NewString(table, "status")
	a.TriggerType = field.NewString(table, "trigger_type")
	a.TriggeredBy = field.NewUint64(table, "triggered_by")
	a.TriggerNote = field.NewString(table, "trigger_note")
	a.TriggerTaskId = field.NewString(table, "trigger_task_id")
	a.SourceCutoffAt = field.NewTime(table, "source_cutoff_at")
	a.RuleVersion = field.NewString(table, "rule_version")
	a.SourceRowCount = field.NewInt64(table, "source_row_count")
	a.CourseStatCount = field.NewInt64(table, "course_stat_count")
	a.InstructorStatCount = field.NewInt64(table, "instructor_stat_count")
	a.ErrorSummary = field.NewString(table, "error_summary")
	a.StartedAt = field.NewTime(table, "started_at")
	a.FinishedAt = field.NewTime(table, "finished_at")
	a.PublishedAt = field.NewTime(table, "published_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *academicStatisticsBatch) WithContext(ctx context.Context) IAcademicStatisticsBatchDo {
	return a.academicStatisticsBatchDo.WithContext(ctx)
}

func (a academicStatisticsBatch) TableName() string { return a.academicStatisticsBatchDo.TableName() }

func (a academicStatisticsBatch) Alias() string { return a.academicStatisticsBatchDo.Alias() }

func (a academicStatisticsBatch) Columns(cols ...field.Expr) gen.Columns {
	return a.academicStatisticsBatchDo.Columns(cols...)
}

func (a *academicStatisticsBatch) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *academicStatisticsBatch) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 17)
	a.fieldMap["id"] = a.ID
	a.fieldMap["status"] = a.Status
	a.fieldMap["trigger_type"] = a.TriggerType
	a.fieldMap["triggered_by"] = a.TriggeredBy
	a.fieldMap["trigger_note"] = a.TriggerNote
	a.fieldMap["trigger_task_id"] = a.TriggerTaskId
	a.fieldMap["source_cutoff_at"] = a.SourceCutoffAt
	a.fieldMap["rule_version"] = a.RuleVersion
	a.fieldMap["source_row_count"] = a.SourceRowCount
	a.fieldMap["course_stat_count"] = a.CourseStatCount
	a.fieldMap["instructor_stat_count"] = a.InstructorStatCount
	a.fieldMap["error_summary"] = a.ErrorSummary
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["finished_at"] = a.FinishedAt
	a.fieldMap["published_at"] = a.PublishedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a academicStatisticsBatch) clone(db *gorm.DB) academicStatisticsBatch {
	a.academicStatisticsBatchDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a academicStatisticsBatch) replaceDB(db *gorm.DB) academicStatisticsBatch {
	a.academicStatisticsBatchDo.ReplaceDB(db)
	return a
}

type academicStatisticsBatchDo struct{ gen.DO }

type IAcademicStatisticsBatchDo interface {
	gen.SubQuery
	Debug() IAcademicStatisticsBatchDo
	WithContext(ctx context.Context) IAcademicStatisticsBatchDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAcademicStatisticsBatchDo
	WriteDB() IAcademicStatisticsBatchDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAcademicStatisticsBatchDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAcademicStatisticsBatchDo
	Not(conds ...gen.Condition) IAcademicStatisticsBatchDo
	Or(conds ...gen.Condition) IAcademicStatisticsBatchDo
	Select(conds ...field.Expr) IAcademicStatisticsBatchDo
	Where(conds ...gen.Condition) IAcademicStatisticsBatchDo
	Order(conds ...field.Expr) IAcademicStatisticsBatchDo
	Distinct(cols ...field.Expr) IAcademicStatisticsBatchDo
	Omit(cols ...field.Expr) IAcademicStatisticsBatchDo
	Join(table schema.Tabler, on ...field.Expr) IAcademicStatisticsBatchDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicStatisticsBatchDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAcademicStatisticsBatchDo
	Group(cols ...field.Expr) IAcademicStatisticsBatchDo
	Having(conds ...gen.Condition) IAcademicStatisticsBatchDo
	Limit(limit int) IAcademicStatisticsBatchDo
	Offset(offset int) IAcademicStatisticsBatchDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicStatisticsBatchDo
	Unscoped() IAcademicStatisticsBatchDo
	Create(values ...*domain.AcademicStatisticsBatch) error
	CreateInBatches(values []*domain.AcademicStatisticsBatch, batchSize int) error
	Save(values ...*domain.AcademicStatisticsBatch) error
	First() (*domain.AcademicStatisticsBatch, error)
	Take() (*domain.AcademicStatisticsBatch, error)
	Last() (*domain.AcademicStatisticsBatch, error)
	Find() ([]*domain.AcademicStatisticsBatch, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicStatisticsBatch, err error)
	FindInBatches(result *[]*domain.AcademicStatisticsBatch, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.AcademicStatisticsBatch) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAcademicStatisticsBatchDo
	Assign(attrs ...field.AssignExpr) IAcademicStatisticsBatchDo
	Joins(fields ...field.RelationField) IAcademicStatisticsBatchDo
	Preload(fields ...field.RelationField) IAcademicStatisticsBatchDo
	FirstOrInit() (*domain.AcademicStatisticsBatch, error)
	FirstOrCreate() (*domain.AcademicStatisticsBatch, error)
	FindByPage(offset int, limit int) (result []*domain.AcademicStatisticsBatch, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAcademicStatisticsBatchDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a academicStatisticsBatchDo) Debug() IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Debug())
}

func (a academicStatisticsBatchDo) WithContext(ctx context.Context) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a academicStatisticsBatchDo) ReadDB() IAcademicStatisticsBatchDo {
	return a.Clauses(dbresolver.Read)
}

func (a academicStatisticsBatchDo) WriteDB() IAcademicStatisticsBatchDo {
	return a.Clauses(dbresolver.Write)
}

func (a academicStatisticsBatchDo) Session(config *gorm.Session) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Session(config))
}

func (a academicStatisticsBatchDo) Clauses(conds ...clause.Expression) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a academicStatisticsBatchDo) Returning(value interface{}, columns ...string) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a academicStatisticsBatchDo) Not(conds ...gen.Condition) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a academicStatisticsBatchDo) Or(conds ...gen.Condition) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a academicStatisticsBatchDo) Select(conds ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a academicStatisticsBatchDo) Where(conds ...gen.Condition) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a academicStatisticsBatchDo) Order(conds ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a academicStatisticsBatchDo) Distinct(cols ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a academicStatisticsBatchDo) Omit(cols ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a academicStatisticsBatchDo) Join(table schema.Tabler, on ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a academicStatisticsBatchDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a academicStatisticsBatchDo) RightJoin(table schema.Tabler, on ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a academicStatisticsBatchDo) Group(cols ...field.Expr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a academicStatisticsBatchDo) Having(conds ...gen.Condition) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a academicStatisticsBatchDo) Limit(limit int) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a academicStatisticsBatchDo) Offset(offset int) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a academicStatisticsBatchDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a academicStatisticsBatchDo) Unscoped() IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Unscoped())
}

func (a academicStatisticsBatchDo) Create(values ...*domain.AcademicStatisticsBatch) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a academicStatisticsBatchDo) CreateInBatches(values []*domain.AcademicStatisticsBatch, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a academicStatisticsBatchDo) Save(values ...*domain.AcademicStatisticsBatch) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a academicStatisticsBatchDo) First() (*domain.AcademicStatisticsBatch, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicStatisticsBatch), nil
	}
}

func (a academicStatisticsBatchDo) Take() (*domain.AcademicStatisticsBatch, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicStatisticsBatch), nil
	}
}

func (a academicStatisticsBatchDo) Last() (*domain.AcademicStatisticsBatch, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicStatisticsBatch), nil
	}
}

func (a academicStatisticsBatchDo) Find() ([]*domain.AcademicStatisticsBatch, error) {
	result, err := a.DO.Find()
	return result.([]*domain.AcademicStatisticsBatch), err
}

func (a academicStatisticsBatchDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicStatisticsBatch, err error) {
	buf := make([]*domain.AcademicStatisticsBatch, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a academicStatisticsBatchDo) FindInBatches(result *[]*domain.AcademicStatisticsBatch, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a academicStatisticsBatchDo) Attrs(attrs ...field.AssignExpr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a academicStatisticsBatchDo) Assign(attrs ...field.AssignExpr) IAcademicStatisticsBatchDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a academicStatisticsBatchDo) Joins(fields ...field.RelationField) IAcademicStatisticsBatchDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a academicStatisticsBatchDo) Preload(fields ...field.RelationField) IAcademicStatisticsBatchDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a academicStatisticsBatchDo) FirstOrInit() (*domain.AcademicStatisticsBatch, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicStatisticsBatch), nil
	}
}

func (a academicStatisticsBatchDo) FirstOrCreate() (*domain.AcademicStatisticsBatch, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicStatisticsBatch), nil
	}
}

func (a academicStatisticsBatchDo) FindByPage(offset int, limit int) (result []*domain.AcademicStatisticsBatch, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a academicStatisticsBatchDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a academicStatisticsBatchDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a academicStatisticsBatchDo) Delete(models ...*domain.AcademicStatisticsBatch) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *academicStatisticsBatchDo) withDO(do gen.Dao) *academicStatisticsBatchDo {
	a.DO = *do.(*gen.DO)
	return a
}
