// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/LDouble/campus-academic/internal/modules/academic_statistics/domain"
)

func newAcademicCourseTermStatistic(db *gorm.DB, opts ...gen.DOOption) academicCourseTermStatistic {
	_academicCourseTermStatistic := academicCourseTermStatistic{}

	_academicCourseTermStatistic.academicCourseTermStatisticDo.UseDB(db, opts...)
	_academicCourseTermStatistic.academicCourseTermStatisticDo.UseModel(&domain.AcademicCourseTermStatistic{})

	tableName := _academicCourseTermStatistic.academicCourseTermStatisticDo.TableName()
	_academicCourseTermStatistic.ALL = field.NewAsterisk(tableName)
	_academicCourseTermStatistic.ID = field.NewUint64(tableName, "id")
	_academicCourseTermStatistic.BatchId = field.NewUint64(tableName, "batch_id")
	_academicCourseTermStatistic.TermCode = field.NewString(tableName, "term_code")
	_academicCourseTermStatistic.EducationLevel = field.NewString(tableName, "education_level")
	_academicCourseTermStatistic.PeriodId = field.NewString(tableName, "period_id")
	_academicCourseTermStatistic.TermLabel = field.NewString(tableName, "term_label")
	_academicCourseTermStatistic.CourseCode = field.NewString(tableName, "course_code")
	_academicCourseTermStatistic.CourseName = field.NewString(tableName, "course_name")
	_academicCourseTermStatistic.ValidCount = field.NewInt64(tableName, "valid_count")
	_academicCourseTermStatistic.PassCount = field.NewInt64(tableName, "pass_count")
	_academicCourseTermStatistic.FailCount = field.NewInt64(tableName, "fail_count")
	_academicCourseTermStatistic.NumericScoreCount = field.NewInt64(tableName, "numeric_score_count")
	_academicCourseTermStatistic.NumericScoreSumX100 = field.NewInt64(tableName, "numeric_score_sum_x100")
	_academicCourseTermStatistic.NumericFailCount = field.NewInt64(tableName, "numeric_fail_count")
	_academicCourseTermStatistic.Score6069Count = field.NewInt64(tableName, "score_60_69_count")
	_academicCourseTermStatistic.Score7079Count = field.NewInt64(tableName, "score_70_79_count")
	_academicCourseTermStatistic.Score8089Count = field.NewInt64(tableName, "score_80_89_count")
	_academicCourseTermStatistic.Score90100Count = field.NewInt64(tableName, "score_90_100_count")
	_academicCourseTermStatistic.LevelExcellentCount = field.NewInt64(tableName, "level_excellent_count")
	_academicCourseTermStatistic.LevelGoodCount = field.NewInt64(tableName, "level_good_count")
	_academicCourseTermStatistic.LevelMediumCount = field.NewInt64(tableName, "level_medium_count")
	_academicCourseTermStatistic.LevelPassCount = field.NewInt64(tableName, "level_pass_count")
	_academicCourseTermStatistic.LevelFailCount = field.NewInt64(tableName, "level_fail_count")
	_academicCourseTermStatistic.CreatedAt = field.NewTime(tableName, "created_at")
	_academicCourseTermStatistic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_academicCourseTermStatistic.fillFieldMap()

	return _academicCourseTermStatistic
}

type academicCourseTermStatistic struct {
	academicCourseTermStatisticDo academicCourseTermStatisticDo

	ALL                 field.Asterisk
	ID                  field.Uint64
	BatchId             field.Uint64
	TermCode            field.String
	EducationLevel      field.String
	PeriodId            field.String
	TermLabel           field.String
	CourseCode          field.String
	CourseName          field.String
	ValidCount          field.Int64
	PassCount           field.Int64
	FailCount           field.Int64
	NumericScoreCount   field.Int64
	NumericScoreSumX100 field.Int64
	NumericFailCount    field.Int64
	Score6069Count      field.Int64
	Score7079Count      field.Int64
	Score8089Count      field.Int64
	Score90100Count     field.Int64
	LevelExcellentCount field.Int64
	LevelGoodCount      field.Int64
	LevelMediumCount    field.Int64
	LevelPassCount      field.Int64
	LevelFailCount      field.Int64
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a academicCourseTermStatistic) Table(newTableName string) *academicCourseTermStatistic {
	a.academicCourseTermStatisticDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a academicCourseTermStatistic) As(alias string) *academicCourseTermStatistic {
	a.academicCourseTermStatisticDo.DO = *(a.academicCourseTermStatisticDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *academicCourseTermStatistic) updateTableName(table string) *academicCourseTermStatistic {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.BatchId = field.NewUint64(table, "batch_id")
	a.TermCode = field.NewString(table, "term_code")
	a.EducationLevel = field.NewString(table, "education_level")
	a.PeriodId = field.NewString(table, "period_id")
	a.TermLabel = field.NewString(table, "term_label")
	a.CourseCode = field.NewString(table, "course_code")
	a.CourseName = field.NewString(table, "course_name")
	a.ValidCount = field.NewInt64(table, "valid_count")
	a.PassCount = field.NewInt64(table, "pass_count")
	a.FailCount = field.NewInt64(table, "fail_count")
	a.NumericScoreCount = field.NewInt64(table, "numeric_score_count")
	a.NumericScoreSumX100 = field.NewInt64(table, "numeric_score_sum_x100")
	a.NumericFailCount = field.NewInt64(table, "numeric_fail_count")
	a.Score6069Count = field.NewInt64(table, "score_60_69_count")
	a.Score7079Count = field.NewInt64(table, "score_70_79_count")
	a.Score8089Count = field.NewInt64(table, "score_80_89_count")
	a.Score90100Count = field.NewInt64(table, "score_90_100_count")
	a.LevelExcellentCount = field.NewInt64(table, "level_excellent_count")
	a.LevelGoodCount = field.NewInt64(table, "level_good_count")
	a.LevelMediumCount = field.NewInt64(table, "level_medium_count")
	a.LevelPassCount = field.NewInt64(table, "level_pass_count")
	a.LevelFailCount = field.NewInt64(table, "level_fail_count")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *academicCourseTermStatistic) WithContext(ctx context.Context) IAcademicCourseTermStatisticDo {
	return a.academicCourseTermStatisticDo.WithContext(ctx)
}

func (a academicCourseTermStatistic) TableName() string {
	return a.academicCourseTermStatisticDo.TableName()
}

func (a academicCourseTermStatistic) Alias() string { return a.academicCourseTermStatisticDo.Alias() }

func (a academicCourseTermStatistic) Columns(cols ...field.Expr) gen.Columns {
	return a.academicCourseTermStatisticDo.Columns(cols...)
}

func (a *academicCourseTermStatistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *academicCourseTermStatistic) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 25)
	a.fieldMap["id"] = a.ID
	a.fieldMap["batch_id"] = a.BatchId
	a.fieldMap["term_code"] = a.TermCode
	a.fieldMap["education_level"] = a.EducationLevel
	a.fieldMap["period_id"] = a.PeriodId
	a.fieldMap["term_label"] = a.TermLabel
	a.fieldMap["course_code"] = a.CourseCode
	a.fieldMap["course_name"] = a.CourseName
	a.fieldMap["valid_count"] = a.ValidCount
	a.fieldMap["pass_count"] = a.PassCount
	a.fieldMap["fail_count"] = a.FailCount
	a.fieldMap["numeric_score_count"] = a.NumericScoreCount
	a.fieldMap["numeric_score_sum_x100"] = a.NumericScoreSumX100
	a.fieldMap["numeric_fail_count"] = a.NumericFailCount
	a.fieldMap["score_60_69_count"] = a.Score6069Count
	a.fieldMap["score_70_79_count"] = a.Score7079Count
	a.fieldMap["score_80_89_count"] = a.Score8089Count
	a.fieldMap["score_90_100_count"] = a.Score90100Count
	a.fieldMap["level_excellent_count"] = a.LevelExcellentCount
	a.fieldMap["level_good_count"] = a.LevelGoodCount
	a.fieldMap["level_medium_count"] = a.LevelMediumCount
	a.fieldMap["level_pass_count"] = a.LevelPassCount
	a.fieldMap["level_fail_count"] = a.LevelFailCount
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a academicCourseTermStatistic) clone(db *gorm.DB) academicCourseTermStatistic {
	a.academicCourseTermStatisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a academicCourseTermStatistic) replaceDB(db *gorm.DB) academicCourseTermStatistic {
	a.academicCourseTermStatisticDo.ReplaceDB(db)
	return a
}

type academicCourseTermStatisticDo struct{ gen.DO }

type IAcademicCourseTermStatisticDo interface {
	gen.SubQuery
	Debug() IAcademicCourseTermStatisticDo
	WithContext(ctx context.Context) IAcademicCourseTermStatisticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAcademicCourseTermStatisticDo
	WriteDB() IAcademicCourseTermStatisticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAcademicCourseTermStatisticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAcademicCourseTermStatisticDo
	Not(conds ...gen.Condition) IAcademicCourseTermStatisticDo
	Or(conds ...gen.Condition) IAcademicCourseTermStatisticDo
	Select(conds ...field.Expr) IAcademicCourseTermStatisticDo
	Where(conds ...gen.Condition) IAcademicCourseTermStatisticDo
	Order(conds ...field.Expr) IAcademicCourseTermStatisticDo
	Distinct(cols ...field.Expr) IAcademicCourseTermStatisticDo
	Omit(cols ...field.Expr) IAcademicCourseTermStatisticDo
	Join(table schema.Tabler, on ...field.Expr) IAcademicCourseTermStatisticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicCourseTermStatisticDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAcademicCourseTermStatisticDo
	Group(cols ...field.Expr) IAcademicCourseTermStatisticDo
	Having(conds ...gen.Condition) IAcademicCourseTermStatisticDo
	Limit(limit int) IAcademicCourseTermStatisticDo
	Offset(offset int) IAcademicCourseTermStatisticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicCourseTermStatisticDo
	Unscoped() IAcademicCourseTermStatisticDo
	Create(values ...*domain.AcademicCourseTermStatistic) error
	CreateInBatches(values []*domain.AcademicCourseTermStatistic, batchSize int) error
	Save(values ...*domain.AcademicCourseTermStatistic) error
	First() (*domain.AcademicCourseTermStatistic, error)
	Take() (*domain.AcademicCourseTermStatistic, error)
	Last() (*domain.AcademicCourseTermStatistic, error)
	Find() ([]*domain.AcademicCourseTermStatistic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicCourseTermStatistic, err error)
	FindInBatches(result *[]*domain.AcademicCourseTermStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.AcademicCourseTermStatistic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAcademicCourseTermStatisticDo
	Assign(attrs ...field.AssignExpr) IAcademicCourseTermStatisticDo
	Joins(fields ...field.RelationField) IAcademicCourseTermStatisticDo
	Preload(fields ...field.RelationField) IAcademicCourseTermStatisticDo
	FirstOrInit() (*domain.AcademicCourseTermStatistic, error)
	FirstOrCreate() (*domain.AcademicCourseTermStatistic, error)
	FindByPage(offset int, limit int) (result []*domain.AcademicCourseTermStatistic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAcademicCourseTermStatisticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a academicCourseTermStatisticDo) Debug() IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Debug())
}

func (a academicCourseTermStatisticDo) WithContext(ctx context.Context) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a academicCourseTermStatisticDo) ReadDB() IAcademicCourseTermStatisticDo {
	return a.Clauses(dbresolver.Read)
}

func (a academicCourseTermStatisticDo) WriteDB() IAcademicCourseTermStatisticDo {
	return a.Clauses(dbresolver.Write)
}

func (a academicCourseTermStatisticDo) Session(config *gorm.Session) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Session(config))
}

func (a academicCourseTermStatisticDo) Clauses(conds ...clause.Expression) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a academicCourseTermStatisticDo) Returning(value interface{}, columns ...string) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a academicCourseTermStatisticDo) Not(conds ...gen.Condition) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a academicCourseTermStatisticDo) Or(conds ...gen.Condition) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a academicCourseTermStatisticDo) Select(conds ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a academicCourseTermStatisticDo) Where(conds ...gen.Condition) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a academicCourseTermStatisticDo) Order(conds ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a academicCourseTermStatisticDo) Distinct(cols ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a academicCourseTermStatisticDo) Omit(cols ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a academicCourseTermStatisticDo) Join(table schema.Tabler, on ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a academicCourseTermStatisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a academicCourseTermStatisticDo) RightJoin(table schema.Tabler, on ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a academicCourseTermStatisticDo) Group(cols ...field.Expr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a academicCourseTermStatisticDo) Having(conds ...gen.Condition) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a academicCourseTermStatisticDo) Limit(limit int) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a academicCourseTermStatisticDo) Offset(offset int) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a academicCourseTermStatisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a academicCourseTermStatisticDo) Unscoped() IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Unscoped())
}

func (a academicCourseTermStatisticDo) Create(values ...*domain.AcademicCourseTermStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a academicCourseTermStatisticDo) CreateInBatches(values []*domain.AcademicCourseTermStatistic, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a academicCourseTermStatisticDo) Save(values ...*domain.AcademicCourseTermStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a academicCourseTermStatisticDo) First() (*domain.AcademicCourseTermStatistic, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCourseTermStatistic), nil
	}
}

func (a academicCourseTermStatisticDo) Take() (*domain.AcademicCourseTermStatistic, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCourseTermStatistic), nil
	}
}

func (a academicCourseTermStatisticDo) Last() (*domain.AcademicCourseTermStatistic, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCourseTermStatistic), nil
	}
}

func (a academicCourseTermStatisticDo) Find() ([]*domain.AcademicCourseTermStatistic, error) {
	result, err := a.DO.Find()
	return result.([]*domain.AcademicCourseTermStatistic), err
}

func (a academicCourseTermStatisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicCourseTermStatistic, err error) {
	buf := make([]*domain.AcademicCourseTermStatistic, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a academicCourseTermStatisticDo) FindInBatches(result *[]*domain.AcademicCourseTermStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a academicCourseTermStatisticDo) Attrs(attrs ...field.AssignExpr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a academicCourseTermStatisticDo) Assign(attrs ...field.AssignExpr) IAcademicCourseTermStatisticDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a academicCourseTermStatisticDo) Joins(fields ...field.RelationField) IAcademicCourseTermStatisticDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a academicCourseTermStatisticDo) Preload(fields ...field.RelationField) IAcademicCourseTermStatisticDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a academicCourseTermStatisticDo) FirstOrInit() (*domain.AcademicCourseTermStatistic, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCourseTermStatistic), nil
	}
}

func (a academicCourseTermStatisticDo) FirstOrCreate() (*domain.AcademicCourseTermStatistic, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCourseTermStatistic), nil
	}
}

func (a academicCourseTermStatisticDo) FindByPage(offset int, limit int) (result []*domain.AcademicCourseTermStatistic, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a academicCourseTermStatisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a academicCourseTermStatisticDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a academicCourseTermStatisticDo) Delete(models ...*domain.AcademicCourseTermStatistic) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *academicCourseTermStatisticDo) withDO(do gen.Dao) *academicCourseTermStatisticDo {
	a.DO = *do.(*gen.DO)
	return a
}
