// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/LDouble/campus-academic/internal/modules/academic_statistics/domain"
)

func newAcademicCoursePassRateStatistic(db *gorm.DB, opts ...gen.DOOption) academicCoursePassRateStatistic {
	_academicCoursePassRateStatistic := academicCoursePassRateStatistic{}

	_academicCoursePassRateStatistic.academicCoursePassRateStatisticDo.UseDB(db, opts...)
	_academicCoursePassRateStatistic.academicCoursePassRateStatisticDo.UseModel(&domain.AcademicCoursePassRateStatistic{})

	tableName := _academicCoursePassRateStatistic.academicCoursePassRateStatisticDo.TableName()
	_academicCoursePassRateStatistic.ALL = field.NewAsterisk(tableName)
	_academicCoursePassRateStatistic.ID = field.NewUint64(tableName, "id")
	_academicCoursePassRateStatistic.BatchId = field.NewUint64(tableName, "batch_id")
	_academicCoursePassRateStatistic.EducationLevel = field.NewString(tableName, "education_level")
	_academicCoursePassRateStatistic.CourseCode = field.NewString(tableName, "course_code")
	_academicCoursePassRateStatistic.CourseName = field.NewString(tableName, "course_name")
	_academicCoursePassRateStatistic.TermCount = field.NewInt64(tableName, "term_count")
	_academicCoursePassRateStatistic.ValidCount = field.NewInt64(tableName, "valid_count")
	_academicCoursePassRateStatistic.PassCount = field.NewInt64(tableName, "pass_count")
	_academicCoursePassRateStatistic.FailCount = field.NewInt64(tableName, "fail_count")
	_academicCoursePassRateStatistic.NumericScoreCount = field.NewInt64(tableName, "numeric_score_count")
	_academicCoursePassRateStatistic.NumericScoreSumX100 = field.NewInt64(tableName, "numeric_score_sum_x100")
	_academicCoursePassRateStatistic.NumericFailCount = field.NewInt64(tableName, "numeric_fail_count")
	_academicCoursePassRateStatistic.Score6069Count = field.NewInt64(tableName, "score_60_69_count")
	_academicCoursePassRateStatistic.Score7079Count = field.NewInt64(tableName, "score_70_79_count")
	_academicCoursePassRateStatistic.Score8089Count = field.NewInt64(tableName, "score_80_89_count")
	_academicCoursePassRateStatistic.Score90100Count = field.NewInt64(tableName, "score_90_100_count")
	_academicCoursePassRateStatistic.LevelExcellentCount = field.NewInt64(tableName, "level_excellent_count")
	_academicCoursePassRateStatistic.LevelGoodCount = field.NewInt64(tableName, "level_good_count")
	_academicCoursePassRateStatistic.LevelMediumCount = field.NewInt64(tableName, "level_medium_count")
	_academicCoursePassRateStatistic.LevelPassCount = field.NewInt64(tableName, "level_pass_count")
	_academicCoursePassRateStatistic.LevelFailCount = field.NewInt64(tableName, "level_fail_count")
	_academicCoursePassRateStatistic.CreatedAt = field.NewTime(tableName, "created_at")
	_academicCoursePassRateStatistic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_academicCoursePassRateStatistic.fillFieldMap()

	return _academicCoursePassRateStatistic
}

type academicCoursePassRateStatistic struct {
	academicCoursePassRateStatisticDo academicCoursePassRateStatisticDo

	ALL                 field.Asterisk
	ID                  field.Uint64
	BatchId             field.Uint64
	EducationLevel      field.String
	CourseCode          field.String
	CourseName          field.String
	TermCount           field.Int64
	ValidCount          field.Int64
	PassCount           field.Int64
	FailCount           field.Int64
	NumericScoreCount   field.Int64
	NumericScoreSumX100 field.Int64
	NumericFailCount    field.Int64
	Score6069Count      field.Int64
	Score7079Count      field.Int64
	Score8089Count      field.Int64
	Score90100Count     field.Int64
	LevelExcellentCount field.Int64
	LevelGoodCount      field.Int64
	LevelMediumCount    field.Int64
	LevelPassCount      field.Int64
	LevelFailCount      field.Int64
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a academicCoursePassRateStatistic) Table(newTableName string) *academicCoursePassRateStatistic {
	a.academicCoursePassRateStatisticDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a academicCoursePassRateStatistic) As(alias string) *academicCoursePassRateStatistic {
	a.academicCoursePassRateStatisticDo.DO = *(a.academicCoursePassRateStatisticDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *academicCoursePassRateStatistic) updateTableName(table string) *academicCoursePassRateStatistic {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.BatchId = field.NewUint64(table, "batch_id")
	a.EducationLevel = field.NewString(table, "education_level")
	a.CourseCode = field.NewString(table, "course_code")
	a.CourseName = field.NewString(table, "course_name")
	a.TermCount = field.NewInt64(table, "term_count")
	a.ValidCount = field.NewInt64(table, "valid_count")
	a.PassCount = field.NewInt64(table, "pass_count")
	a.FailCount = field.NewInt64(table, "fail_count")
	a.NumericScoreCount = field.NewInt64(table, "numeric_score_count")
	a.NumericScoreSumX100 = field.NewInt64(table, "numeric_score_sum_x100")
	a.NumericFailCount = field.NewInt64(table, "numeric_fail_count")
	a.Score6069Count = field.NewInt64(table, "score_60_69_count")
	a.Score7079Count = field.NewInt64(table, "score_70_79_count")
	a.Score8089Count = field.NewInt64(table, "score_80_89_count")
	a.Score90100Count = field.NewInt64(table, "score_90_100_count")
	a.LevelExcellentCount = field.NewInt64(table, "level_excellent_count")
	a.LevelGoodCount = field.NewInt64(table, "level_good_count")
	a.LevelMediumCount = field.NewInt64(table, "level_medium_count")
	a.LevelPassCount = field.NewInt64(table, "level_pass_count")
	a.LevelFailCount = field.NewInt64(table, "level_fail_count")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *academicCoursePassRateStatistic) WithContext(ctx context.Context) IAcademicCoursePassRateStatisticDo {
	return a.academicCoursePassRateStatisticDo.WithContext(ctx)
}

func (a academicCoursePassRateStatistic) TableName() string {
	return a.academicCoursePassRateStatisticDo.TableName()
}

func (a academicCoursePassRateStatistic) Alias() string {
	return a.academicCoursePassRateStatisticDo.Alias()
}

func (a academicCoursePassRateStatistic) Columns(cols ...field.Expr) gen.Columns {
	return a.academicCoursePassRateStatisticDo.Columns(cols...)
}

func (a *academicCoursePassRateStatistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *academicCoursePassRateStatistic) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 23)
	a.fieldMap["id"] = a.ID
	a.fieldMap["batch_id"] = a.BatchId
	a.fieldMap["education_level"] = a.EducationLevel
	a.fieldMap["course_code"] = a.CourseCode
	a.fieldMap["course_name"] = a.CourseName
	a.fieldMap["term_count"] = a.TermCount
	a.fieldMap["valid_count"] = a.ValidCount
	a.fieldMap["pass_count"] = a.PassCount
	a.fieldMap["fail_count"] = a.FailCount
	a.fieldMap["numeric_score_count"] = a.NumericScoreCount
	a.fieldMap["numeric_score_sum_x100"] = a.NumericScoreSumX100
	a.fieldMap["numeric_fail_count"] = a.NumericFailCount
	a.fieldMap["score_60_69_count"] = a.Score6069Count
	a.fieldMap["score_70_79_count"] = a.Score7079Count
	a.fieldMap["score_80_89_count"] = a.Score8089Count
	a.fieldMap["score_90_100_count"] = a.Score90100Count
	a.fieldMap["level_excellent_count"] = a.LevelExcellentCount
	a.fieldMap["level_good_count"] = a.LevelGoodCount
	a.fieldMap["level_medium_count"] = a.LevelMediumCount
	a.fieldMap["level_pass_count"] = a.LevelPassCount
	a.fieldMap["level_fail_count"] = a.LevelFailCount
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a academicCoursePassRateStatistic) clone(db *gorm.DB) academicCoursePassRateStatistic {
	a.academicCoursePassRateStatisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a academicCoursePassRateStatistic) replaceDB(db *gorm.DB) academicCoursePassRateStatistic {
	a.academicCoursePassRateStatisticDo.ReplaceDB(db)
	return a
}

type academicCoursePassRateStatisticDo struct{ gen.DO }

type IAcademicCoursePassRateStatisticDo interface {
	gen.SubQuery
	Debug() IAcademicCoursePassRateStatisticDo
	WithContext(ctx context.Context) IAcademicCoursePassRateStatisticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAcademicCoursePassRateStatisticDo
	WriteDB() IAcademicCoursePassRateStatisticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAcademicCoursePassRateStatisticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAcademicCoursePassRateStatisticDo
	Not(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo
	Or(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo
	Select(conds ...field.Expr) IAcademicCoursePassRateStatisticDo
	Where(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo
	Order(conds ...field.Expr) IAcademicCoursePassRateStatisticDo
	Distinct(cols ...field.Expr) IAcademicCoursePassRateStatisticDo
	Omit(cols ...field.Expr) IAcademicCoursePassRateStatisticDo
	Join(table schema.Tabler, on ...field.Expr) IAcademicCoursePassRateStatisticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicCoursePassRateStatisticDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAcademicCoursePassRateStatisticDo
	Group(cols ...field.Expr) IAcademicCoursePassRateStatisticDo
	Having(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo
	Limit(limit int) IAcademicCoursePassRateStatisticDo
	Offset(offset int) IAcademicCoursePassRateStatisticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicCoursePassRateStatisticDo
	Unscoped() IAcademicCoursePassRateStatisticDo
	Create(values ...*domain.AcademicCoursePassRateStatistic) error
	CreateInBatches(values []*domain.AcademicCoursePassRateStatistic, batchSize int) error
	Save(values ...*domain.AcademicCoursePassRateStatistic) error
	First() (*domain.AcademicCoursePassRateStatistic, error)
	Take() (*domain.AcademicCoursePassRateStatistic, error)
	Last() (*domain.AcademicCoursePassRateStatistic, error)
	Find() ([]*domain.AcademicCoursePassRateStatistic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicCoursePassRateStatistic, err error)
	FindInBatches(result *[]*domain.AcademicCoursePassRateStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.AcademicCoursePassRateStatistic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAcademicCoursePassRateStatisticDo
	Assign(attrs ...field.AssignExpr) IAcademicCoursePassRateStatisticDo
	Joins(fields ...field.RelationField) IAcademicCoursePassRateStatisticDo
	Preload(fields ...field.RelationField) IAcademicCoursePassRateStatisticDo
	FirstOrInit() (*domain.AcademicCoursePassRateStatistic, error)
	FirstOrCreate() (*domain.AcademicCoursePassRateStatistic, error)
	FindByPage(offset int, limit int) (result []*domain.AcademicCoursePassRateStatistic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAcademicCoursePassRateStatisticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a academicCoursePassRateStatisticDo) Debug() IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Debug())
}

func (a academicCoursePassRateStatisticDo) WithContext(ctx context.Context) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a academicCoursePassRateStatisticDo) ReadDB() IAcademicCoursePassRateStatisticDo {
	return a.Clauses(dbresolver.Read)
}

func (a academicCoursePassRateStatisticDo) WriteDB() IAcademicCoursePassRateStatisticDo {
	return a.Clauses(dbresolver.Write)
}

func (a academicCoursePassRateStatisticDo) Session(config *gorm.Session) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Session(config))
}

func (a academicCoursePassRateStatisticDo) Clauses(conds ...clause.Expression) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a academicCoursePassRateStatisticDo) Returning(value interface{}, columns ...string) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a academicCoursePassRateStatisticDo) Not(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a academicCoursePassRateStatisticDo) Or(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a academicCoursePassRateStatisticDo) Select(conds ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a academicCoursePassRateStatisticDo) Where(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a academicCoursePassRateStatisticDo) Order(conds ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a academicCoursePassRateStatisticDo) Distinct(cols ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a academicCoursePassRateStatisticDo) Omit(cols ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a academicCoursePassRateStatisticDo) Join(table schema.Tabler, on ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a academicCoursePassRateStatisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a academicCoursePassRateStatisticDo) RightJoin(table schema.Tabler, on ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a academicCoursePassRateStatisticDo) Group(cols ...field.Expr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a academicCoursePassRateStatisticDo) Having(conds ...gen.Condition) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a academicCoursePassRateStatisticDo) Limit(limit int) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a academicCoursePassRateStatisticDo) Offset(offset int) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a academicCoursePassRateStatisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a academicCoursePassRateStatisticDo) Unscoped() IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Unscoped())
}

func (a academicCoursePassRateStatisticDo) Create(values ...*domain.AcademicCoursePassRateStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a academicCoursePassRateStatisticDo) CreateInBatches(values []*domain.AcademicCoursePassRateStatistic, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a academicCoursePassRateStatisticDo) Save(values ...*domain.AcademicCoursePassRateStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a academicCoursePassRateStatisticDo) First() (*domain.AcademicCoursePassRateStatistic, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCoursePassRateStatistic), nil
	}
}

func (a academicCoursePassRateStatisticDo) Take() (*domain.AcademicCoursePassRateStatistic, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCoursePassRateStatistic), nil
	}
}

func (a academicCoursePassRateStatisticDo) Last() (*domain.AcademicCoursePassRateStatistic, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCoursePassRateStatistic), nil
	}
}

func (a academicCoursePassRateStatisticDo) Find() ([]*domain.AcademicCoursePassRateStatistic, error) {
	result, err := a.DO.Find()
	return result.([]*domain.AcademicCoursePassRateStatistic), err
}

func (a academicCoursePassRateStatisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicCoursePassRateStatistic, err error) {
	buf := make([]*domain.AcademicCoursePassRateStatistic, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a academicCoursePassRateStatisticDo) FindInBatches(result *[]*domain.AcademicCoursePassRateStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a academicCoursePassRateStatisticDo) Attrs(attrs ...field.AssignExpr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a academicCoursePassRateStatisticDo) Assign(attrs ...field.AssignExpr) IAcademicCoursePassRateStatisticDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a academicCoursePassRateStatisticDo) Joins(fields ...field.RelationField) IAcademicCoursePassRateStatisticDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a academicCoursePassRateStatisticDo) Preload(fields ...field.RelationField) IAcademicCoursePassRateStatisticDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a academicCoursePassRateStatisticDo) FirstOrInit() (*domain.AcademicCoursePassRateStatistic, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCoursePassRateStatistic), nil
	}
}

func (a academicCoursePassRateStatisticDo) FirstOrCreate() (*domain.AcademicCoursePassRateStatistic, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicCoursePassRateStatistic), nil
	}
}

func (a academicCoursePassRateStatisticDo) FindByPage(offset int, limit int) (result []*domain.AcademicCoursePassRateStatistic, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a academicCoursePassRateStatisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a academicCoursePassRateStatisticDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a academicCoursePassRateStatisticDo) Delete(models ...*domain.AcademicCoursePassRateStatistic) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *academicCoursePassRateStatisticDo) withDO(do gen.Dao) *academicCoursePassRateStatisticDo {
	a.DO = *do.(*gen.DO)
	return a
}
