// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/LDouble/campus-academic/internal/modules/academic_statistics/domain"
)

func newAcademicInstructorCourseTermStatistic(db *gorm.DB, opts ...gen.DOOption) academicInstructorCourseTermStatistic {
	_academicInstructorCourseTermStatistic := academicInstructorCourseTermStatistic{}

	_academicInstructorCourseTermStatistic.academicInstructorCourseTermStatisticDo.UseDB(db, opts...)
	_academicInstructorCourseTermStatistic.academicInstructorCourseTermStatisticDo.UseModel(&domain.AcademicInstructorCourseTermStatistic{})

	tableName := _academicInstructorCourseTermStatistic.academicInstructorCourseTermStatisticDo.TableName()
	_academicInstructorCourseTermStatistic.ALL = field.NewAsterisk(tableName)
	_academicInstructorCourseTermStatistic.ID = field.NewUint64(tableName, "id")
	_academicInstructorCourseTermStatistic.BatchId = field.NewUint64(tableName, "batch_id")
	_academicInstructorCourseTermStatistic.TermCode = field.NewString(tableName, "term_code")
	_academicInstructorCourseTermStatistic.EducationLevel = field.NewString(tableName, "education_level")
	_academicInstructorCourseTermStatistic.PeriodId = field.NewString(tableName, "period_id")
	_academicInstructorCourseTermStatistic.TermLabel = field.NewString(tableName, "term_label")
	_academicInstructorCourseTermStatistic.CourseCode = field.NewString(tableName, "course_code")
	_academicInstructorCourseTermStatistic.CourseName = field.NewString(tableName, "course_name")
	_academicInstructorCourseTermStatistic.TeacherKey = field.NewString(tableName, "teacher_key")
	_academicInstructorCourseTermStatistic.TeacherName = field.NewString(tableName, "teacher_name")
	_academicInstructorCourseTermStatistic.ClassCount = field.NewInt64(tableName, "class_count")
	_academicInstructorCourseTermStatistic.ValidCount = field.NewInt64(tableName, "valid_count")
	_academicInstructorCourseTermStatistic.PassCount = field.NewInt64(tableName, "pass_count")
	_academicInstructorCourseTermStatistic.FailCount = field.NewInt64(tableName, "fail_count")
	_academicInstructorCourseTermStatistic.NumericScoreCount = field.NewInt64(tableName, "numeric_score_count")
	_academicInstructorCourseTermStatistic.NumericScoreSumX100 = field.NewInt64(tableName, "numeric_score_sum_x100")
	_academicInstructorCourseTermStatistic.NumericFailCount = field.NewInt64(tableName, "numeric_fail_count")
	_academicInstructorCourseTermStatistic.Score6069Count = field.NewInt64(tableName, "score_60_69_count")
	_academicInstructorCourseTermStatistic.Score7079Count = field.NewInt64(tableName, "score_70_79_count")
	_academicInstructorCourseTermStatistic.Score8089Count = field.NewInt64(tableName, "score_80_89_count")
	_academicInstructorCourseTermStatistic.Score90100Count = field.NewInt64(tableName, "score_90_100_count")
	_academicInstructorCourseTermStatistic.LevelExcellentCount = field.NewInt64(tableName, "level_excellent_count")
	_academicInstructorCourseTermStatistic.LevelGoodCount = field.NewInt64(tableName, "level_good_count")
	_academicInstructorCourseTermStatistic.LevelMediumCount = field.NewInt64(tableName, "level_medium_count")
	_academicInstructorCourseTermStatistic.LevelPassCount = field.NewInt64(tableName, "level_pass_count")
	_academicInstructorCourseTermStatistic.LevelFailCount = field.NewInt64(tableName, "level_fail_count")
	_academicInstructorCourseTermStatistic.CreatedAt = field.NewTime(tableName, "created_at")
	_academicInstructorCourseTermStatistic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_academicInstructorCourseTermStatistic.fillFieldMap()

	return _academicInstructorCourseTermStatistic
}

type academicInstructorCourseTermStatistic struct {
	academicInstructorCourseTermStatisticDo academicInstructorCourseTermStatisticDo

	ALL                 field.Asterisk
	ID                  field.Uint64
	BatchId             field.Uint64
	TermCode            field.String
	EducationLevel      field.String
	PeriodId            field.String
	TermLabel           field.String
	CourseCode          field.String
	CourseName          field.String
	TeacherKey          field.String
	TeacherName         field.String
	ClassCount          field.Int64
	ValidCount          field.Int64
	PassCount           field.Int64
	FailCount           field.Int64
	NumericScoreCount   field.Int64
	NumericScoreSumX100 field.Int64
	NumericFailCount    field.Int64
	Score6069Count      field.Int64
	Score7079Count      field.Int64
	Score8089Count      field.Int64
	Score90100Count     field.Int64
	LevelExcellentCount field.Int64
	LevelGoodCount      field.Int64
	LevelMediumCount    field.Int64
	LevelPassCount      field.Int64
	LevelFailCount      field.Int64
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a academicInstructorCourseTermStatistic) Table(newTableName string) *academicInstructorCourseTermStatistic {
	a.academicInstructorCourseTermStatisticDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a academicInstructorCourseTermStatistic) As(alias string) *academicInstructorCourseTermStatistic {
	a.academicInstructorCourseTermStatisticDo.DO = *(a.academicInstructorCourseTermStatisticDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *academicInstructorCourseTermStatistic) updateTableName(table string) *academicInstructorCourseTermStatistic {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.BatchId = field.NewUint64(table, "batch_id")
	a.TermCode = field.NewString(table, "term_code")
	a.EducationLevel = field.NewString(table, "education_level")
	a.PeriodId = field.NewString(table, "period_id")
	a.TermLabel = field.NewString(table, "term_label")
	a.CourseCode = field.NewString(table, "course_code")
	a.CourseName = field.NewString(table, "course_name")
	a.TeacherKey = field.NewString(table, "teacher_key")
	a.TeacherName = field.NewString(table, "teacher_name")
	a.ClassCount = field.NewInt64(table, "class_count")
	a.ValidCount = field.NewInt64(table, "valid_count")
	a.PassCount = field.NewInt64(table, "pass_count")
	a.FailCount = field.NewInt64(table, "fail_count")
	a.NumericScoreCount = field.NewInt64(table, "numeric_score_count")
	a.NumericScoreSumX100 = field.NewInt64(table, "numeric_score_sum_x100")
	a.NumericFailCount = field.NewInt64(table, "numeric_fail_count")
	a.Score6069Count = field.NewInt64(table, "score_60_69_count")
	a.Score7079Count = field.NewInt64(table, "score_70_79_count")
	a.Score8089Count = field.NewInt64(table, "score_80_89_count")
	a.Score90100Count = field.NewInt64(table, "score_90_100_count")
	a.LevelExcellentCount = field.NewInt64(table, "level_excellent_count")
	a.LevelGoodCount = field.NewInt64(table, "level_good_count")
	a.LevelMediumCount = field.NewInt64(table, "level_medium_count")
	a.LevelPassCount = field.NewInt64(table, "level_pass_count")
	a.LevelFailCount = field.NewInt64(table, "level_fail_count")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *academicInstructorCourseTermStatistic) WithContext(ctx context.Context) IAcademicInstructorCourseTermStatisticDo {
	return a.academicInstructorCourseTermStatisticDo.WithContext(ctx)
}

func (a academicInstructorCourseTermStatistic) TableName() string {
	return a.academicInstructorCourseTermStatisticDo.TableName()
}

func (a academicInstructorCourseTermStatistic) Alias() string {
	return a.academicInstructorCourseTermStatisticDo.Alias()
}

func (a academicInstructorCourseTermStatistic) Columns(cols ...field.Expr) gen.Columns {
	return a.academicInstructorCourseTermStatisticDo.Columns(cols...)
}

func (a *academicInstructorCourseTermStatistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *academicInstructorCourseTermStatistic) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 28)
	a.fieldMap["id"] = a.ID
	a.fieldMap["batch_id"] = a.BatchId
	a.fieldMap["term_code"] = a.TermCode
	a.fieldMap["education_level"] = a.EducationLevel
	a.fieldMap["period_id"] = a.PeriodId
	a.fieldMap["term_label"] = a.TermLabel
	a.fieldMap["course_code"] = a.CourseCode
	a.fieldMap["course_name"] = a.CourseName
	a.fieldMap["teacher_key"] = a.TeacherKey
	a.fieldMap["teacher_name"] = a.TeacherName
	a.fieldMap["class_count"] = a.ClassCount
	a.fieldMap["valid_count"] = a.ValidCount
	a.fieldMap["pass_count"] = a.PassCount
	a.fieldMap["fail_count"] = a.FailCount
	a.fieldMap["numeric_score_count"] = a.NumericScoreCount
	a.fieldMap["numeric_score_sum_x100"] = a.NumericScoreSumX100
	a.fieldMap["numeric_fail_count"] = a.NumericFailCount
	a.fieldMap["score_60_69_count"] = a.Score6069Count
	a.fieldMap["score_70_79_count"] = a.Score7079Count
	a.fieldMap["score_80_89_count"] = a.Score8089Count
	a.fieldMap["score_90_100_count"] = a.Score90100Count
	a.fieldMap["level_excellent_count"] = a.LevelExcellentCount
	a.fieldMap["level_good_count"] = a.LevelGoodCount
	a.fieldMap["level_medium_count"] = a.LevelMediumCount
	a.fieldMap["level_pass_count"] = a.LevelPassCount
	a.fieldMap["level_fail_count"] = a.LevelFailCount
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a academicInstructorCourseTermStatistic) clone(db *gorm.DB) academicInstructorCourseTermStatistic {
	a.academicInstructorCourseTermStatisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a academicInstructorCourseTermStatistic) replaceDB(db *gorm.DB) academicInstructorCourseTermStatistic {
	a.academicInstructorCourseTermStatisticDo.ReplaceDB(db)
	return a
}

type academicInstructorCourseTermStatisticDo struct{ gen.DO }

type IAcademicInstructorCourseTermStatisticDo interface {
	gen.SubQuery
	Debug() IAcademicInstructorCourseTermStatisticDo
	WithContext(ctx context.Context) IAcademicInstructorCourseTermStatisticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAcademicInstructorCourseTermStatisticDo
	WriteDB() IAcademicInstructorCourseTermStatisticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAcademicInstructorCourseTermStatisticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAcademicInstructorCourseTermStatisticDo
	Not(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo
	Or(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo
	Select(conds ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	Where(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo
	Order(conds ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	Distinct(cols ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	Omit(cols ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	Join(table schema.Tabler, on ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	Group(cols ...field.Expr) IAcademicInstructorCourseTermStatisticDo
	Having(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo
	Limit(limit int) IAcademicInstructorCourseTermStatisticDo
	Offset(offset int) IAcademicInstructorCourseTermStatisticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicInstructorCourseTermStatisticDo
	Unscoped() IAcademicInstructorCourseTermStatisticDo
	Create(values ...*domain.AcademicInstructorCourseTermStatistic) error
	CreateInBatches(values []*domain.AcademicInstructorCourseTermStatistic, batchSize int) error
	Save(values ...*domain.AcademicInstructorCourseTermStatistic) error
	First() (*domain.AcademicInstructorCourseTermStatistic, error)
	Take() (*domain.AcademicInstructorCourseTermStatistic, error)
	Last() (*domain.AcademicInstructorCourseTermStatistic, error)
	Find() ([]*domain.AcademicInstructorCourseTermStatistic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicInstructorCourseTermStatistic, err error)
	FindInBatches(result *[]*domain.AcademicInstructorCourseTermStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*domain.AcademicInstructorCourseTermStatistic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAcademicInstructorCourseTermStatisticDo
	Assign(attrs ...field.AssignExpr) IAcademicInstructorCourseTermStatisticDo
	Joins(fields ...field.RelationField) IAcademicInstructorCourseTermStatisticDo
	Preload(fields ...field.RelationField) IAcademicInstructorCourseTermStatisticDo
	FirstOrInit() (*domain.AcademicInstructorCourseTermStatistic, error)
	FirstOrCreate() (*domain.AcademicInstructorCourseTermStatistic, error)
	FindByPage(offset int, limit int) (result []*domain.AcademicInstructorCourseTermStatistic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAcademicInstructorCourseTermStatisticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a academicInstructorCourseTermStatisticDo) Debug() IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Debug())
}

func (a academicInstructorCourseTermStatisticDo) WithContext(ctx context.Context) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a academicInstructorCourseTermStatisticDo) ReadDB() IAcademicInstructorCourseTermStatisticDo {
	return a.Clauses(dbresolver.Read)
}

func (a academicInstructorCourseTermStatisticDo) WriteDB() IAcademicInstructorCourseTermStatisticDo {
	return a.Clauses(dbresolver.Write)
}

func (a academicInstructorCourseTermStatisticDo) Session(config *gorm.Session) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Session(config))
}

func (a academicInstructorCourseTermStatisticDo) Clauses(conds ...clause.Expression) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Returning(value interface{}, columns ...string) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a academicInstructorCourseTermStatisticDo) Not(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Or(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Select(conds ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Where(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Order(conds ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Distinct(cols ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a academicInstructorCourseTermStatisticDo) Omit(cols ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a academicInstructorCourseTermStatisticDo) Join(table schema.Tabler, on ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a academicInstructorCourseTermStatisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a academicInstructorCourseTermStatisticDo) RightJoin(table schema.Tabler, on ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a academicInstructorCourseTermStatisticDo) Group(cols ...field.Expr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a academicInstructorCourseTermStatisticDo) Having(conds ...gen.Condition) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a academicInstructorCourseTermStatisticDo) Limit(limit int) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a academicInstructorCourseTermStatisticDo) Offset(offset int) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a academicInstructorCourseTermStatisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a academicInstructorCourseTermStatisticDo) Unscoped() IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Unscoped())
}

func (a academicInstructorCourseTermStatisticDo) Create(values ...*domain.AcademicInstructorCourseTermStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a academicInstructorCourseTermStatisticDo) CreateInBatches(values []*domain.AcademicInstructorCourseTermStatistic, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a academicInstructorCourseTermStatisticDo) Save(values ...*domain.AcademicInstructorCourseTermStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a academicInstructorCourseTermStatisticDo) First() (*domain.AcademicInstructorCourseTermStatistic, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicInstructorCourseTermStatistic), nil
	}
}

func (a academicInstructorCourseTermStatisticDo) Take() (*domain.AcademicInstructorCourseTermStatistic, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicInstructorCourseTermStatistic), nil
	}
}

func (a academicInstructorCourseTermStatisticDo) Last() (*domain.AcademicInstructorCourseTermStatistic, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicInstructorCourseTermStatistic), nil
	}
}

func (a academicInstructorCourseTermStatisticDo) Find() ([]*domain.AcademicInstructorCourseTermStatistic, error) {
	result, err := a.DO.Find()
	return result.([]*domain.AcademicInstructorCourseTermStatistic), err
}

func (a academicInstructorCourseTermStatisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.AcademicInstructorCourseTermStatistic, err error) {
	buf := make([]*domain.AcademicInstructorCourseTermStatistic, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a academicInstructorCourseTermStatisticDo) FindInBatches(result *[]*domain.AcademicInstructorCourseTermStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a academicInstructorCourseTermStatisticDo) Attrs(attrs ...field.AssignExpr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a academicInstructorCourseTermStatisticDo) Assign(attrs ...field.AssignExpr) IAcademicInstructorCourseTermStatisticDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a academicInstructorCourseTermStatisticDo) Joins(fields ...field.RelationField) IAcademicInstructorCourseTermStatisticDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a academicInstructorCourseTermStatisticDo) Preload(fields ...field.RelationField) IAcademicInstructorCourseTermStatisticDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a academicInstructorCourseTermStatisticDo) FirstOrInit() (*domain.AcademicInstructorCourseTermStatistic, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicInstructorCourseTermStatistic), nil
	}
}

func (a academicInstructorCourseTermStatisticDo) FirstOrCreate() (*domain.AcademicInstructorCourseTermStatistic, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.AcademicInstructorCourseTermStatistic), nil
	}
}

func (a academicInstructorCourseTermStatisticDo) FindByPage(offset int, limit int) (result []*domain.AcademicInstructorCourseTermStatistic, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a academicInstructorCourseTermStatisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a academicInstructorCourseTermStatisticDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a academicInstructorCourseTermStatisticDo) Delete(models ...*domain.AcademicInstructorCourseTermStatistic) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *academicInstructorCourseTermStatisticDo) withDO(do gen.Dao) *academicInstructorCourseTermStatisticDo {
	a.DO = *do.(*gen.DO)
	return a
}
