// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                                     = new(Query)
	AcademicCoursePassRateStatistic       *academicCoursePassRateStatistic
	AcademicCourseTermStatistic           *academicCourseTermStatistic
	AcademicInstructorCourseTermStatistic *academicInstructorCourseTermStatistic
	AcademicStatisticsBatch               *academicStatisticsBatch
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AcademicCoursePassRateStatistic = &Q.AcademicCoursePassRateStatistic
	AcademicCourseTermStatistic = &Q.AcademicCourseTermStatistic
	AcademicInstructorCourseTermStatistic = &Q.AcademicInstructorCourseTermStatistic
	AcademicStatisticsBatch = &Q.AcademicStatisticsBatch
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                                    db,
		AcademicCoursePassRateStatistic:       newAcademicCoursePassRateStatistic(db, opts...),
		AcademicCourseTermStatistic:           newAcademicCourseTermStatistic(db, opts...),
		AcademicInstructorCourseTermStatistic: newAcademicInstructorCourseTermStatistic(db, opts...),
		AcademicStatisticsBatch:               newAcademicStatisticsBatch(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AcademicCoursePassRateStatistic       academicCoursePassRateStatistic
	AcademicCourseTermStatistic           academicCourseTermStatistic
	AcademicInstructorCourseTermStatistic academicInstructorCourseTermStatistic
	AcademicStatisticsBatch               academicStatisticsBatch
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                                    db,
		AcademicCoursePassRateStatistic:       q.AcademicCoursePassRateStatistic.clone(db),
		AcademicCourseTermStatistic:           q.AcademicCourseTermStatistic.clone(db),
		AcademicInstructorCourseTermStatistic: q.AcademicInstructorCourseTermStatistic.clone(db),
		AcademicStatisticsBatch:               q.AcademicStatisticsBatch.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                                    db,
		AcademicCoursePassRateStatistic:       q.AcademicCoursePassRateStatistic.replaceDB(db),
		AcademicCourseTermStatistic:           q.AcademicCourseTermStatistic.replaceDB(db),
		AcademicInstructorCourseTermStatistic: q.AcademicInstructorCourseTermStatistic.replaceDB(db),
		AcademicStatisticsBatch:               q.AcademicStatisticsBatch.replaceDB(db),
	}
}

type queryCtx struct {
	AcademicCoursePassRateStatistic       IAcademicCoursePassRateStatisticDo
	AcademicCourseTermStatistic           IAcademicCourseTermStatisticDo
	AcademicInstructorCourseTermStatistic IAcademicInstructorCourseTermStatisticDo
	AcademicStatisticsBatch               IAcademicStatisticsBatchDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AcademicCoursePassRateStatistic:       q.AcademicCoursePassRateStatistic.WithContext(ctx),
		AcademicCourseTermStatistic:           q.AcademicCourseTermStatistic.WithContext(ctx),
		AcademicInstructorCourseTermStatistic: q.AcademicInstructorCourseTermStatistic.WithContext(ctx),
		AcademicStatisticsBatch:               q.AcademicStatisticsBatch.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
